name: test push docker

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 23 * * *'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: docker login & push
      run: |
        docker login -u ${{ secrets.name }} -p ${{ secrets.pass }} 
        docker login docker.tarsyun.com -u ${{ secrets.tarsname }} -p ${{ secrets.tarspass }} 
        docker pull tarscloud/framework:nightly
        docker tag tarscloud/framework:nightly docker.tarsyun.com/tarscloud/framework:nightly
        docker push docker.tarsyun.com/tarscloud/framework:nightly

